version: "3"
services:
  app:
    build: .
    volumes:
      - ./Src/:/var/src
    ports:
      - '3000:3000'
    tty: true
    command: >
      bash -c "bundle install -j4　--path=vendor/bundle &&
        bundle exec rails db:setup &&
        rm -f /tmp/pids/server/pid &&
        bundle exec rails s -b 0.0.0.0"
